framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_HOST_DSN)%'
        directory: '%kernel.cache_dir%/tiles' # TODO in reality this does not do the thing we want

when@test:
    framework:
        cache:
            app: cache.adapter.filesystem
