twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': styles
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        project_name: '%project_name%'
        project_base_url: '%project_base_url%'
        public_uploads: /uploads
        offline_cache_name: '%offline_cache_name%'
        app_env: '%app_env%'
        prod: prod
        dev: dev
        test: test
        instance_open: '%instance_open%'
        mapbox_key: '%env(MAPBOX_KEY)%'
        google_map_key: '%google_map_key%'

when@test:
    twig:
        strict_variables: true
