networks:
    traefik_default:
        external: false
        driver: bridge
        name: traefik_default

services:
    router:
        image: traefik:v2.7
        restart: "always"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./docker/traefik/etc/ssl/certs:/etc/ssl/certs"
            - "./docker/traefik/etc/traefik:/etc/traefik"
        networks:
            - "traefik_default"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
