volumes:
    trailodyssey-data: {}
    trailodyssey-sessions: {}
    trailodyssey-uploads: {}

services:
    php-fpm:
        build: docker/php-fpm
        volumes:
            - "./:/var/www"
            - "trailodyssey-data:/var/www/var/data"
            - "trailodyssey-sessions:/var/www/var/sessions"
            - "trailodyssey-uploads:/var/www/public/uploads"
            - "./docker/php-fpm/etc/ImageMagick-6:/etc/ImageMagick-6"
            - "./docker/php-fpm/usr/local/etc:/usr/local/etc"
            - "./docker/php-fpm/nginx.conf:/etc/nginx/nginx.conf"
        environment:
            - IN_BUILDER=1
            - APP_ENV=${APP_ENV:-prod}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - DEPLOY=${DEPLOY:-prod}
            - GOOGLE_MAP_KEY=${GOOGLE_MAP_KEY}
            - INSTANCE_OPEN=${INSTANCE_OPEN:-false}
            - MAILER_DSN=${MAILER_DSN:-null://null}
            - MAINTENANCE=${MAINTENANCE:-false}
            - MAPBOX_KEY=${MAPBOX_KEY}
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN:-doctrine://default?auto_setup=0}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - PROJECT_BASE_URL=${PROJECT_BASE_URL:-https://trailodyssey.net}
            - PROJECT_HOST=${PROJECT_HOST:-trailodyssey.net}
            - REDIS_HOST_DSN=${REDIS_HOST_DSN}
            - SYMFONY_FRAMEWORK_IDE=${SYMFONY_FRAMEWORK_IDE:-null://}
            - MASTODON_INSTANCES=${MASTODON_INSTANCES}
            - MASTODON_CLIENT_KEYS=${MASTODON_CLIENT_KEYS}
            - MASTODON_CLIENT_SECRETS=${MASTODON_CLIENT_SECRETS}
