volumes:
    projects-trailodyssey-builder-root: {}

services:
    php-fpm:
        restart: "no"
        volumes:
            - "projects-trailodyssey-builder-root:/root"
        labels:
            # trailodyssey.test
            traefik.http.routers.trailodyssey-test.rule: Host(`trailodyssey.test`)
            traefik.http.routers.trailodyssey-test.tls: true
            traefik.http.routers.trailodyssey-test.service: trailodyssey-common
            traefik.http.routers.trailodyssey-test-unsecure.rule: Host(`trailodyssey.test`)
            traefik.http.routers.trailodyssey-test-unsecure.service: trailodyssey-common

    postgres:
        restart: "no"
        ports:
            - 5437:${POSTGRES_PORT}

    redis:
        restart: "no"
        ports:
            - "6399:6379"
