services:
    router:
        image: traefik:v2.7
        restart: "no"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./docker/traefik/etc/ssl/certs:/etc/ssl/certs"
            - "./docker/traefik/etc/traefik:/etc/traefik"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
