<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'First migration after migration from MySQL to PostgreSQL';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bag (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          weight INT DEFAULT NULL,
          checked BOOLEAN NOT NULL,
          user_id INT NOT NULL,
          trip_id INT NOT NULL,
          parent_bag_id INT DEFAULT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_1B226841A76ED395 ON bag (user_id)');
        $this->addSql('CREATE INDEX IDX_1B226841A5BC2E0E ON bag (trip_id)');
        $this->addSql('CREATE INDEX IDX_1B226841204E4151 ON bag (parent_bag_id)');
        $this->addSql('CREATE TABLE diary_entry (
          type VARCHAR(16) DEFAULT NULL,
          symbol VARCHAR(16) DEFAULT NULL,
          broadcast_identifiers JSON DEFAULT NULL,
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          arriving_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          point_name VARCHAR(255) NOT NULL,
          point_lat VARCHAR(255) NOT NULL,
          point_lon VARCHAR(255) NOT NULL,
          trip_id INT NOT NULL,
          user_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_6A3E3D51A5BC2E0E ON diary_entry (trip_id)');
        $this->addSql('CREATE INDEX IDX_6A3E3D51A76ED395 ON diary_entry (user_id)');
        $this->addSql('CREATE TABLE gear (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          weight INT DEFAULT NULL,
          user_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_B44539BA76ED395 ON gear (user_id)');
        $this->addSql('CREATE TABLE gear_in_bag (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          count INT NOT NULL,
          checked BOOLEAN NOT NULL,
          gear_id INT NOT NULL,
          bag_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_2BA25E2E77201934 ON gear_in_bag (gear_id)');
        $this->addSql('CREATE INDEX IDX_2BA25E2E6F5D8297 ON gear_in_bag (bag_id)');
        $this->addSql('CREATE TABLE interest (
          type VARCHAR(16) DEFAULT NULL,
          symbol VARCHAR(16) DEFAULT NULL,
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          arriving_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          point_name VARCHAR(255) NOT NULL,
          point_lat VARCHAR(255) NOT NULL,
          point_lon VARCHAR(255) NOT NULL,
          trip_id INT NOT NULL,
          user_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_6C3E1A67A5BC2E0E ON interest (trip_id)');
        $this->addSql('CREATE INDEX IDX_6C3E1A67A76ED395 ON interest (user_id)');
        $this->addSql('CREATE TABLE photo (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          path VARCHAR(255) NOT NULL,
          user_id INT NOT NULL,
          trip_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_14B78418A76ED395 ON photo (user_id)');
        $this->addSql('CREATE INDEX IDX_14B78418A5BC2E0E ON photo (trip_id)');
        $this->addSql('CREATE TABLE routing (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          distance INT DEFAULT NULL,
          as_the_crow_fly BOOLEAN NOT NULL,
          path_points_store TEXT DEFAULT NULL,
          elevation_positive INT DEFAULT NULL,
          elevation_negative INT DEFAULT NULL,
          user_id INT NOT NULL,
          trip_id INT NOT NULL,
          start_stage_id INT NOT NULL,
          finish_stage_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_A5F8B9FAA76ED395 ON routing (user_id)');
        $this->addSql('CREATE INDEX IDX_A5F8B9FAA5BC2E0E ON routing (trip_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5F8B9FA3DB297A1 ON routing (start_stage_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5F8B9FA9BD392C3 ON routing (finish_stage_id)');
        $this->addSql('CREATE TABLE segment (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          points JSON NOT NULL,
          bounding_box JSON NOT NULL,
          distance INT DEFAULT NULL,
          user_id INT NOT NULL,
          trip_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_1881F565A76ED395 ON segment (user_id)');
        $this->addSql('CREATE INDEX IDX_1881F565A5BC2E0E ON segment (trip_id)');
        $this->addSql('CREATE TABLE stage (
          timezone VARCHAR(255) NOT NULL,
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          arriving_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          point_name VARCHAR(255) NOT NULL,
          point_lat VARCHAR(255) NOT NULL,
          point_lon VARCHAR(255) NOT NULL,
          trip_id INT NOT NULL,
          user_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_C27C9369A5BC2E0E ON stage (trip_id)');
        $this->addSql('CREATE INDEX IDX_C27C9369A76ED395 ON stage (user_id)');
        $this->addSql('CREATE TABLE tiles (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          url VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          overlay BOOLEAN NOT NULL,
          public BOOLEAN NOT NULL,
          use_proxy BOOLEAN NOT NULL,
          geo_json BOOLEAN NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          geo_json_html TEXT DEFAULT NULL,
          position INT NOT NULL,
          trip_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_1C1584BBA5BC2E0E ON tiles (trip_id)');
        $this->addSql('CREATE TABLE trip (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          description TEXT DEFAULT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          share_key VARCHAR(255) DEFAULT NULL,
          map_zoom INT NOT NULL,
          is_calculating_segment BOOLEAN DEFAULT false NOT NULL,
          progress_point_store JSON DEFAULT NULL,
          map_center_lat VARCHAR(255) NOT NULL,
          map_center_lon VARCHAR(255) NOT NULL,
          user_id INT NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_7656F53BA76ED395 ON trip (user_id)');
        $this->addSql('CREATE TABLE user_list (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          username VARCHAR(180) NOT NULL,
          nickname VARCHAR(80) NOT NULL,
          roles JSON NOT NULL,
          password VARCHAR(255) NOT NULL,
          timezone VARCHAR(32) DEFAULT \'UTC\' NOT NULL,
          export_filename_pattern VARCHAR(64) DEFAULT \'{counter}{stage_name}{trip_name}\' NOT NULL,
          mastodon_info JSON DEFAULT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E49B4D1F85E0677 ON user_list (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E49B4D1A188FE64 ON user_list (nickname)');
        $this->addSql('CREATE TABLE messenger_messages (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          body TEXT NOT NULL,
          headers TEXT NOT NULL,
          queue_name VARCHAR(190) NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE bag ADD CONSTRAINT FK_1B226841A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bag ADD CONSTRAINT FK_1B226841A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bag ADD CONSTRAINT FK_1B226841204E4151 FOREIGN KEY (parent_bag_id) REFERENCES bag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diary_entry ADD CONSTRAINT FK_6A3E3D51A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diary_entry ADD CONSTRAINT FK_6A3E3D51A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gear ADD CONSTRAINT FK_B44539BA76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gear_in_bag ADD CONSTRAINT FK_2BA25E2E77201934 FOREIGN KEY (gear_id) REFERENCES gear (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gear_in_bag ADD CONSTRAINT FK_2BA25E2E6F5D8297 FOREIGN KEY (bag_id) REFERENCES bag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interest ADD CONSTRAINT FK_6C3E1A67A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interest ADD CONSTRAINT FK_6C3E1A67A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FAA76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FAA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FA3DB297A1 FOREIGN KEY (start_stage_id) REFERENCES stage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FA9BD392C3 FOREIGN KEY (finish_stage_id) REFERENCES stage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE segment ADD CONSTRAINT FK_1881F565A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE segment ADD CONSTRAINT FK_1881F565A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369A76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tiles ADD CONSTRAINT FK_1C1584BBA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53BA76ED395 FOREIGN KEY (user_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
    }
}
