parameters:
    project_name: Trail Odyssey
    project_host: '%env(PROJECT_HOST)%'
    project_base_url: '%env(PROJECT_BASE_URL)%'
    locale_default: en
    locale_available: ['en', 'fr']
    locale_requirement: en|fr
    offline_cache_name: cache-20240613-004
    instance_open: '%env(bool:INSTANCE_OPEN)%'
    app_env: '%env(APP_ENV)%'
    google_map_key: '%env(GOOGLE_MAP_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectName: '%project_name%'
            $projectHost: '%project_host%'
            $projectBaseUrl: '%project_base_url%'
            $publicDirectory: '%kernel.project_dir%/public'
            $uploadsDirectory: '%kernel.project_dir%/public/uploads'
            $instanceOpen: '%instance_open%'
            $withGoogleMap: '@=parameter("google_map_key") !== ""'
            $env: '%app_env%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'

    twig.markdown.league_common_mark_converter_factory:
        class: App\Override\LeagueCommonMarkConverterFactory

    App\Twig\HelperExtension:
        arguments:
            $intlExtension: '@twig.extension.intl'

    Liip\ImagineBundle\Service\FilterService:
        alias: liip_imagine.service.filter

    App\Service\GeoCodingService:
        arguments:
            $googleMapKey: '%google_map_key%'

when@dev:
    services:
        Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'
