name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    steps:
      # Generate a new key pair: ssh-keygen -t ed25519
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy
        run: ssh production 'cd web && ../.local/bin/castor prod:deploy ../vault/env_prod'
